name: PR Validation

on:
  pull_request:
    branches:
      - main
      - beta

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: TypeScript Build Check
        run: npm run build -- --noEmit

      - name: Run Linter
        run: npm run lint

      # Placeholder for Tests - Add when you have frontend tests setup
      - name: Run Tests
        run: echo "No tests configured yet."

      - name: Validate Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
